apiVersion: v1
kind: Service
metadata:
  name: aep-iotshow
  labels:
    k8s-app: aep-iotshow
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    k8s-app: aep-iotshow
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: aep-iotshow
spec:
  replicas: 1
  selector:
    k8s-app: aep-iotshow
  template:
    metadata:
      labels:
        k8s-app: aep-iotshow
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: aep-iotshow
        image: jdnw.com:5000/aep/iotshow:latest
        ports:
        - containerPort: 8080
        env:
        - name: ETCD_URI
          value: "http://10.3.6.76:2379"
