apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log-iotshow
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "iotshow"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-log-iotshow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi